/* 테이블 제거 */

DROP TABLE APPLY_STEPS;

DROP TABLE BOARD;

DROP TABLE GRADE;

DROP TABLE EXAM_QUESTION;

DROP TABLE EXAM;

DROP TABLE COURSE;

DROP TABLE INSTRUCTOR;

DROP TABLE STUDENT;

DROP TABLE ADMIN;

/* 시퀀스 제거 */
DROP SEQUENCE SEQ_ADM_ID;

DROP SEQUENCE SEQ_BOARD_NUM;

DROP SEQUENCE SEQ_COUR_NUM;

DROP SEQUENCE SEQ_EXAM_NUM;

DROP SEQUENCE SEQ_INST_NUM;

DROP SEQUENCE SEQ_QUES_NUM;

DROP SEQUENCE SEQ_STU_NUM;

DROP SEQUENCE SEQ_GRADE_NUM;

/* 시퀀스 생성 */
CREATE SEQUENCE SEQ_QUES_NUM
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999999;

CREATE SEQUENCE SEQ_EXAM_NUM
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999999;

CREATE SEQUENCE SEQ_INST_NUM
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999999;

CREATE SEQUENCE SEQ_STU_NUM
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999999;

CREATE SEQUENCE SEQ_COUR_NUM
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999999;

CREATE SEQUENCE SEQ_BOARD_NUM
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999999;

CREATE SEQUENCE SEQ_ADM_ID
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999999;

CREATE SEQUENCE SEQ_GRADE_NUM
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999999;


-- 테이블명 : 시험 문제
-- PK : QUES_NUM, FK : EXAM_NUM
CREATE TABLE EXAM_QUESTION (
QUES_NUM VARCHAR2(10)	NOT NULL,
QUES_CONTENT	VARCHAR(255)	NOT NULL,
QUES_OPTION	VARCHAR(255)	NOT NULL,
QUES_OPTION_CORRECT	NUMBER(1)	NOT NULL,
EXAM_NUM	NUMBER	NOT NULL
);


-- 테이블명 : 강사
-- PK : INST_NUM
CREATE TABLE INSTRUCTOR (
INST_NUM	VARCHAR2(20) NOT NULL,
INST_PASS	VARCHAR(30)	NOT NULL,
INST_NAME	VARCHAR(30)	NOT NULL,
INST_BIRTH	DATE	NOT NULL,
INST_TEL	VARCHAR(20)	NOT NULL,
INST_ADD	VARCHAR(255)	NOT NULL
);

-- 테이블명 : 과정
-- PK : COUR_NUM, FK : INST_NUM
CREATE TABLE COURSE (
COUR_NUM	NUMBER NOT NULL,
COUR_CARDINAL	VARCHAR(6) NOT NULL,
COUR_NAME	VARCHAR2(300)	NOT NULL,
COUR_STATUS	VARCHAR(30)	NOT NULL,
COUR_STARTDATE	DATE	NOT NULL,
COUR_ENDDATE DATE	NOT NULL,
INST_NUM	VARCHAR2(10) NOT NULL
);


-- 테이블명 : 성적
-- FK : EXAM_NUM
CREATE TABLE GRADE (
GRADE_NUM NUMBER(8) NOT NULL,
EXAM_ANSW_COUNT NUMBER(1) NOT NULL,
STU_NUM	VARCHAR2(10) NOT	NULL,
EXAM_NUM	NUMBER(10) NOT NULL
);


-- 테이블명 : 게시판
-- PK : PK_BOARD_NUM, FK : STU_NUM, INST_NUM, ADM_ID
CREATE TABLE BOARD (
BOARD_NUM	NUMBER	NOT NULL,
BOARD_TITLE	VARCHAR2(300)	NOT NULL,
BOARD_CONTENT	VARCHAR2(300) NOT	NULL,
BOARD_STATUS	VARCHAR2(25) DEFAULT '답변대기',
BOARD_DATE	DATE	DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD'),
BOARD_TYPE	VARCHAR2(25),
BOARD_COMM_CONTENT	VARCHAR2(255),
BOARD_COMM_DATE	DATE	DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD'),
STU_NUM	VARCHAR2(10),
INST_NUM	VARCHAR2(10),
ADM_ID	VARCHAR2(20)
	);



-- 테이블명 ; 신청과정
-- FK ; STU_NUM, COUR_NUM
CREATE TABLE APPLY_STEPS (
STU_NUM	VARCHAR2(10)	NOT NULL,
COUR_NUM NUMBER	NOT NULL
);


-- 테이블명 ; 관리자
-- PK ; ADM_ID
CREATE TABLE ADMIN (
ADM_ID VARCHAR(30)	NOT NULL,
ADM_PASS	VARCHAR(30)	NOT NULL,
ADM_NAME	VARCHAR(30)	NOT NULL,
ADM_BIRTH	DATE	NOT NULL,
ADM_TEL	VARCHAR(20)	NOT NULL,
ADM_ADD	VARCHAR(255)	NOT NULL
);

-- 테이블명 ; 학생
-- PK ; STU_NUM
CREATE TABLE STUDENT (
STU_NUM	VARCHAR2(20)	NOT NULL,
STU_PASS	VARCHAR(30)	NOT NULL,
STU_NAME	VARCHAR(30)	NOT NULL,
STU_BIRTH	DATE	NOT NULL,
STU_TEL	VARCHAR(20)	NOT NULL,
STU_ADD	VARCHAR(255)	NOT NULL,
STU_STATUS	VARCHAR(30)	NOT NULL
);

-- 테이블명 ; 시험지
-- PK ; EXAM_NUM, FK ; COUR_NUM, STU_NUM
CREATE TABLE EXAM (
EXAM_NUM	NUMBER(10)	NOT NULL,
EXAM_NAME	VARCHAR(255)	NOT NULL,
EXAM_DATE	DATE	NOT NULL,
COUR_NUM	NUMBER	NOT NULL
);


/* 권한 설정 */

-- PRIMARY KEY

ALTER TABLE EXAM_QUESTION ADD CONSTRAINT PK_EXAM_QUESTION PRIMARY KEY (QUES_NUM);

ALTER TABLE INSTRUCTOR ADD CONSTRAINT PK_INSTRUCTOR PRIMARY KEY (INST_NUM);

ALTER TABLE COURSE ADD CONSTRAINT PK_COURSE PRIMARY KEY (COUR_NUM);

ALTER TABLE BOARD ADD CONSTRAINT PK_BOARD PRIMARY KEY (BOARD_NUM);

ALTER TABLE ADMIN ADD CONSTRAINT PK_ADMIN PRIMARY KEY (ADM_ID);

ALTER TABLE STUDENT ADD CONSTRAINT PK_STUDENT PRIMARY KEY (STU_NUM);

ALTER TABLE EXAM ADD CONSTRAINT PK_EXAM PRIMARY KEY (EXAM_NUM);


-- FOREIGN KEY

ALTER TABLE EXAM_QUESTION ADD CONSTRAINT FK_EXAM_TO_EXAM_QUESTION FOREIGN KEY (EXAM_NUM)
REFERENCES EXAM (EXAM_NUM);

ALTER TABLE COURSE ADD CONSTRAINT FK_INSTRUCTOR_TO_COURSE FOREIGN KEY (INST_NUM)
REFERENCES INSTRUCTOR (INST_NUM);

ALTER TABLE BOARD ADD CONSTRAINT FK_STUDENT_TO_BOARD FOREIGN KEY (STU_NUM)
REFERENCES STUDENT (STU_NUM);

ALTER TABLE BOARD ADD CONSTRAINT FK_INSTRUCTOR_TO_BOARD FOREIGN KEY (INST_NUM)
REFERENCES INSTRUCTOR (INST_NUM);

ALTER TABLE BOARD ADD CONSTRAINT FK_ADMIN_TO_BOARD FOREIGN KEY (ADM_ID)
REFERENCES ADMIN (ADM_ID);

ALTER TABLE APPLY_STEPS ADD CONSTRAINT FK_STUDENT_TO_APPLY_STEPS FOREIGN KEY (STU_NUM)
REFERENCES STUDENT (STU_NUM);

ALTER TABLE APPLY_STEPS ADD CONSTRAINT FK_COURSE_TO_APPLY_STEPS FOREIGN KEY (COUR_NUM)
REFERENCES COURSE (COUR_NUM);

ALTER TABLE EXAM ADD CONSTRAINT FK_COURSE_TO_EXAM FOREIGN KEY (COUR_NUM)
REFERENCES COURSE (COUR_NUM);


ALTER TABLE GRADE ADD CONSTRAINT FK_EXAM_TO_GRADE FOREIGN KEY (EXAM_NUM)
REFERENCES EXAM (EXAM_NUM);

ALTER TABLE GRADE ADD CONSTRAINT FK_STUDENT_TO_GRADE FOREIGN KEY (STU_NUM)
REFERENCES STUDENT (STU_NUM);


-- UNIQUE

ALTER TABLE COURSE ADD CONSTRAINT UQ_COUR_CARDINAL UNIQUE (COUR_CARDINAL);

