ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; -- 계정명 C## 안쓰고 만들 수 있게 하는 거, 만드시고 FALSE 하면 됩니다

CREATE USER sistprj IDENTIFIED BY tiger;

GRANT CONNECT TO sistprj;

GRANT RESOURCE TO sistprj;

GRANT CREATE VIEW TO sistprj;

GRANT CREATE SEQUENCE TO sistprj;

ALTER USER sistprj DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

